### ISSUE TITLE
Crash: "Unexpected character after type and field:  sensor_msgs/JointState"

### ISSUE THREAD

**Issue by torydebra** [facontidavide/ros_msg_parser#1]
Hi,
First, thanks for your work. I found few days ago your ros_type_introspection and it is very useful. 

I am trying to use this new version, but when I run: 
`rosrun ros_msg_parser generic_subscriber /js_publisher/joint_states` 
an error occurs:
~~~
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unexpected character after type and field:  sensor_msgs/JointState /js_publisher/joint_states
Annullato (core dump creato)
~~~

The same kind of message worked with ros_type_introspection. The type, as printed above, is _sensor_msgs/JointState_
Am I doing something wrong this time?

**Comment by facontidavide** [comment]
Congratulations for being the first issue reporter :)

Fixed

**Comment by torydebra** [comment]
Thanks :D

By the way, even after pulling the last commit I still have the same problem

**Comment by facontidavide** [comment]
😱

**Comment by facontidavide** [comment]
This is unfortunate, because I can not replicate that on my machine (it works now). Can you share a rosbag that I can play to reproduce this error?

**Comment by facontidavide** [comment]
NOW it is fixed

**Comment by torydebra** [comment]
:+1:  Thanks again!
